### Onsale
GET /api/products/onsale HTTP/1.1
Host: {{ host }}

### List
GET /api/products/ HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

### Store
POST /api/products/ HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "title": "Product Name",
    "description": "Description",
    "sell_price": 20.50,
    "production_price": 10.50,
    "top_price": 150.50,
    "onsale": true,
    "category_id": 1
}

### Show
GET /api/products/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}


### Update
PATCH /api/products/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

{
    "title": "Product Name updated",
    "description": "Description updated",
    "sell_price": 50.50,
    "production_price": 40.50,
    "top_price": 100.50,
    "onsale": true,
    "category_id": 1
}

### Destroy
DELETE /api/products/1 HTTP/1.1
Host: {{ host }}
Authorization: {{token}}

