export enum ROUTE_NAME {
  AUTH_LOGIN = 'AUTH_LOGIN',
  HOME = 'ADMIN_HOME',
  MENU = 'ADMIN_MENU',
  ORDERS = 'ADMIN_ORDERS',
  SETTINGS = 'ADMIN_SETTINGS',
  CATEGORIES = 'ADMIN.CATEGORIES',

  CLIENT_MENU = 'CLIENT.MENU',
  CLIENT_CART = 'CLIENT.CART',
  CLIENT_ORDERS = 'CLIENT.ORDERS',
}
